### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by DongDavid** [aqiongbei/bomer#39]
老哥好，
       一个销售不停的加我微信， 我举报了他一下， 然后他被微信[短期封号]了，(我还手贱的把这个发到微信群里了，估计被他知道了)，然后我就开始被短信轰炸了， 连续200多条注册验证码短信。 我想请教一下这个短信轰炸违法嘛， 去哪里举报啊， 警察叔叔说没有证据不受理。 
       像这种电话轰炸的， 是不是只要没有证据也不受理啊？

谢谢老哥， 盼复！

**Comment by DongDavid** [comment]
如何才能够找到证据呢，或者说那几个点容易找到证据的？

**Comment by aqiongbei** [comment]
> 如何才能够找到证据呢，或者说那几个点容易找到证据的？

- 是否违法不知道,但是肯定不对的
- 这种证据不好找,成本大,耗时长,基本可以放弃
- 但实际上是有举报网站的[12321](https://www.12321.cn/),可以去看看有没有对应的方案

**Comment by gh0sthx** [comment]
只能以暴制暴

**Comment by DongDavid** [comment]
谢谢两位老哥。 @aqiongbei @Paladinhanxiao 
后来我警告了一下对方， 就停手了。 
我也就没管它了， 互相伤害起来感觉我也亏啊(大概就是这种心理让这种人能肆无忌惮的搞事情吧)。
